set -e
true
true
/Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/bin/spades-hammer /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/corrected/configs/config.info
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/corrected/corrected.yaml --ext_python_modules_home /Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/share/spades --max_threads 16 --output_dir /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/corrected --gzip_output
true
true
/Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/bin/spades-core /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K21/configs/config.info
/Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/bin/spades-core /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K33/configs/config.info
/Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/bin/spades-core /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K55/configs/config.info
/Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/bin/spades-core /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/configs/config.info
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/share/spades/spades_pipeline/scripts/copy_files.py /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/before_rr.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/before_rr.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/assembly_graph_after_simplification.gfa /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/assembly_graph_after_simplification.gfa /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/final_contigs.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/contigs.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/first_pe_contigs.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/first_pe_contigs.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/strain_graph.gfa /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/strain_graph.gfa /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/scaffolds.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/scaffolds.fasta /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/scaffolds.paths /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/scaffolds.paths /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/assembly_graph_with_scaffolds.gfa /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/assembly_graph_with_scaffolds.gfa /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/assembly_graph.fastg /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/assembly_graph.fastg /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/K77/final_contigs.paths /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/contigs.paths
true
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/johncheney/Downloads/SPAdes-3.15.0-Darwin/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/scaffolds.fasta --misc_dir /Users/johncheney/Documents/GitHub/Genomics-Research-Project/Rosa_Reads/spades_output/misc --threshold_for_breaking_scaffolds 3
true
